name: Rust Format Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt
        run: cargo fmt -v --all -- --check
